### ISSUE TITLE
AnnotateLocus.py issues

### ISSUE THREAD

**Issue by leaskimo** [gkichaev/PAINTOR_V3.0#28]
Had a few issues with AnnotateLocus.py
 First I had to remove lines in the Annotations_Path file because I kept getting this:
Traceback (most recent call last):
  File "AnnotateLocus.py", line 54, in <module>
    current_annotation = open(annotations.strip())
IOError: [Errno 21] Is a directory: 'Functional_Annotations/'

Now I am getting the error below:

Traceback (most recent call last):
  File "AnnotateLocus.py", line 64, in <module>
    left_int.append(int(site[1]))
ValueError: invalid literal for int() with base 10: 'h'

What could it mean?

**Comment by JulieGb** [comment]
Hi leaskimo, 
Did you fix your issue ? Because I've the same : 
"Traceback (most recent call last):
File "AnnotateLocus.py", line 54, in 
current_annotation = open(annotations.strip())
IOError: [Errno 21] Is a directory: 'Functional_Annotations/'"

Thank you

**Comment by SitaZhou** [comment]
Hi,
The line in the Annotations_Path should be the path of your annotation file, including the file name. 
And the second error:
Traceback (most recent call last):
File "AnnotateLocus.py", line 64, in 
left_int.append(int(site[1]))
ValueError: invalid literal for int() with base 10: 'h'
I guess it might due to the improper delimiter of your file .

**Comment by xxz1482** [comment]
Hi Guys,
My error was like:
Traceback (most recent call last):
  File "AnnotateLocus.py", line 55, in <module>
    current_annotation = open(annotations.strip())
IOError: [Errno 2] No such file or directory: 'l\x1b\x01\xb3/\xef\xba\xaa\xfa\xea\xff?\xea'
Any clues/suggestions? 

Thanks in advance!
