### ISSUE TITLE
CANVIS script won't run

### ISSUE THREAD

**Issue by bogdanknez** [gkichaev/PAINTOR_V3.0#39]
I've managed to run through the entire PAINTOR pipeline up until the visualization point. For running CANVIS.py, I've set up a virtual environment with all the most updated packages required, as suggested on the PAINTOR wiki page for visualization. Once inside my environment, I've tried executing the code with

`python CANVIS.py \
-l ctla4.results \
-z Zscore \
-r ctla4.LD1 \
-a ctla4.annotations`

However, when I execute the above, the script runs for several seconds before outputting the below. Is there anything I can do in order to get this to run? Not sure what is causing these error messages? Again, the files that I am inputting to execute this are the exact output files of the previous PAINTOR pipeline (unmodified in any way). Thanks for your help.

Traceback (most recent call last):
  File "/gpfs2/well/jknight/bogdan/PAINTOR_V3.0/python-virtual-environments/env/lib/python3.5/site-packages/pandas/core/indexes/base.py", line 2657, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'BP'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "CANVIS.py", line 520, in <module>
    main()
  File "CANVIS.py", line 493, in main
    ld_name, annotations, annotation_names, interval, bp_head)
  File "CANVIS.py", line 44, in Read_Input
    location = zscore_data[bp_head]
  File "/gpfs2/well/jknight/bogdan/PAINTOR_V3.0/python-virtual-environments/env/lib/python3.5/site-packages/pandas/core/frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/gpfs2/well/jknight/bogdan/PAINTOR_V3.0/python-virtual-environments/env/lib/python3.5/site-packages/pandas/core/indexes/base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'BP'

**Comment by JiaShun-Xiao** [comment]
see this pull request
https://github.com/gkichaev/PAINTOR_V3.0/pull/44
