### ISSUE TITLE
Truncated annotations file: .E094-H3K9me3.narrowPeak.Gastric.P486F3

### ISSUE THREAD

**Issue by andronekomimi** [gkichaev/PAINTOR_V3.0#46]
Hello,

Annotation with the file **.E094-H3K9me3.narrowPeak.Gastric.P486F3** produces the following error: 
```
xxxxxxt/PAINTOR_V3.0/Functional_Annotations/RoadMap_Assayed_NarrowPeak/.E094-H3K9me3.narrowPeak.Gastric.P486F3

Traceback (most recent call last):
  File "PAINTOR_Utilities/AnnotateLocus.py", line 66, in <module>
    right_int.append(int(site[2]))
ValueError: null byte in argument for int()
```
The file seems to be truncated
```
[xxx@xxxx PAINTOR_V3.0]$ tail xxxxx/PAINTOR_V3.0/Functional_Annotations/RoadMap_Assayed_NarrowPeak/.E094-H3K9me3.narrowPeak.Gastric.P486F3**
chrX 79893150 79893314 Rank_77933 45 . 3.79564 4.53609 1.82753 67
chrX 79894737 79894904 Rank_77934 45 . 3.79564 4.53609 1.82753 119
chrX 80003545 80003775 Rank_77935 45 . 3.79564 4.53609 1.82753 111
chrX 80148847 80149072 Rank_140662 29 . 2.81159 2.94719 0.77812 119
chrX 80150475 80150636 Rank_77936 45 . 3.79564 4.53609 1.82753 60
chrX 80161881 80162015 Rank_91877 41 . 3.33205 4.14265 1.57037 65
chrX 80187049 80187371 Rank_39584 55 . 4.33788 5.51819 2.50474 257
chrX 80204124 80204278 Rank_81739 43 . 3.61064 4.39292 1.77144 47
chrX 80337957 80338091 Rank_152214 26 . 2.61539 2.60599 0.68794 57
chrX 80362920 [nekomimi@wkivw-pgx-0102 PAINTOR_V3.0]$
```

And instead of being an ASCII text file its type is binary
```
xxx@xxxx PAINTOR_V3.0]$ file xxxxx/PAINTOR_V3.0/Functional_Annotations/RoadMap_Assayed_NarrowPeak/.E094-H3K9me3.narrowPeak.Gastric.P486F3
xxxxx/PAINTOR_V3.0/Functional_Annotations/RoadMap_Assayed_NarrowPeak/.E094-H3K9me3.narrowPeak.Gastric.P486F3: data
```

**Comment by manuelatan** [comment]
Hi, I am having the same issue with the same file.

```
Functional_Annotations/RoadMap_Assayed_NarrowPeak/.E094-H3K9me3.narrowPeak.Gastric.P486F3

Traceback (most recent call last):
  File "PAINTOR_V3.0/PAINTOR_Utilities/AnnotateLocus.py", line 66, in <module>
    right_int.append(int(site[2]))
ValueError: null byte in argument for int()

```
Did you manage to resolve this, and if so how?


Code:

`python /data/kronos/kronos/mtan/software/PAINTOR_V3.0/PAINTOR_Utilities/AnnotateLocus.py --input ./Functional_Annotations/Annotation_Paths --locus Locus1 --out Locus1.annotations --chr CHR --pos POS
`

I have also tried to remove the last row which appears to be truncated in the file Functional_Annotations/RoadMap_Assayed_NarrowPeak/.E094-H3K9me3.narrowPeak.Gastric.P486F3 but I get the same error.
